# Generated by Django 4.1.3 on 2022-11-21 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
            ],
            options={
                'verbose_name': 'Вопросы',
                'verbose_name_plural': 'Вопрос',
            },
        ),
        migrations.CreateModel(
            name='SetOfQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тема')),
                ('questions', models.ManyToManyField(to='quiz_app.question')),
            ],
            options={
                'verbose_name': 'Темы тестов',
                'verbose_name_plural': 'Тема тестов',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст ответа')),
                ('true_or_false', models.BooleanField(verbose_name='Правильность')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.question')),
            ],
            options={
                'verbose_name': 'Ответы',
                'verbose_name_plural': 'Ответ',
            },
        ),
    ]
