# Generated by Django 4.1.3 on 2022-11-21 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SetOfQuestion',
            new_name='Test',
        ),
    ]
